name: Home Buy Design
favicon: null
layout_spectrum: 0.48695
typography_spectrum: 0.5924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#000000'
    - '#a7a7a7'
    - '#303030'
    - '#535353'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
