name: Home Buy Design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5924
title: Renovating the way you buy and sell your home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#005da0'
    - '#231f20'
    - '#c7c6c7'
    - '#6c6b6c'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
