name: Home Buy Design
favicon: null
layout_spectrum: 0.7280246189329773
typography_spectrum: 0.07820793031714857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#000000'
    - '#a7a7a7'
    - '#303030'
    - '#535353'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
